<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7d96cd1191b14cfa9f5cfacf60dc86de
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'LucasCassaro\\DigitalCep\\' => 24,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LucasCassaro\\DigitalCep\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7d96cd1191b14cfa9f5cfacf60dc86de::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7d96cd1191b14cfa9f5cfacf60dc86de::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7d96cd1191b14cfa9f5cfacf60dc86de::$classMap;

        }, null, ClassLoader::class);
    }
}
